// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsWise.Models;

#nullable disable

namespace NewsWise.Migrations
{
    [DbContext(typeof(NewswiseDbContext))]
    [Migration("20230522054045_stringLength256")]
    partial class stringLength256
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsWise.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<DateTime?>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClaimantId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaimId");

                    b.HasIndex("ClaimantId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("NewsWise.Models.ClaimReview", b =>
                {
                    b.Property<int>("ClaimReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimReviewId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewPublisherId")
                        .HasColumnType("int");

                    b.Property<string>("TextualRating")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaimReviewId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("ReviewPublisherId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("NewsWise.Models.Claimant", b =>
                {
                    b.Property<int>("ClaimantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimantId"));

                    b.Property<string>("ClaimantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaimantId");

                    b.ToTable("Claimants");
                });

            modelBuilder.Entity("NewsWise.Models.ReviewPublisher", b =>
                {
                    b.Property<int>("ReviewPublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewPublisherId"));

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewPublisherId");

                    b.ToTable("ReviewPublisher");
                });

            modelBuilder.Entity("NewsWise.Models.Claim", b =>
                {
                    b.HasOne("NewsWise.Models.Claimant", null)
                        .WithMany("Claims")
                        .HasForeignKey("ClaimantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsWise.Models.ClaimReview", b =>
                {
                    b.HasOne("NewsWise.Models.Claim", null)
                        .WithMany("Claim_Reviews")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewsWise.Models.ReviewPublisher", null)
                        .WithMany("ClaimReviews")
                        .HasForeignKey("ReviewPublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewsWise.Models.Claim", b =>
                {
                    b.Navigation("Claim_Reviews");
                });

            modelBuilder.Entity("NewsWise.Models.Claimant", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("NewsWise.Models.ReviewPublisher", b =>
                {
                    b.Navigation("ClaimReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
